# https://hub.docker.com/r/circleci/node
image: "circleci/node:13.8.0"

before_script:
  - npm ci

lint:
  script:
    - npm run lint

js_test:
  script:
    - ./scripts/test-with-coverage.sh

build:
  script:
    - npm run build

#fresh: # TODO fix, this doesn't work
#  script:
#    - ./scripts/check-dependencies.sh
