version: 2.1
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/node
      - image: circleci/node:13.8.0
    steps:
      - checkout # Check out repo
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint
          when: always
      - run:
          name: test
          command: ./scripts/test-with-coverage.sh
          when: always
      - run:
          name: build
          command: npm run build
          when: always
      - run:
          name: verify dependency freshness
          command: ./scripts/check-dependencies.sh
          when: always
