version: 2.1
jobs:
  build:
    docker:
      # https://hub.docker.com/r/circleci/node
      - image: circleci/node:13.8.0
    steps:
      - checkout # Check out repo
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: |
            export testResult=$(npm run coverage) || true
            echo "testResult was ${testResult}"
            bash <(curl -s https://codecov.io/bash)
            if [ "$testResult" != "0" ]; then exit 1; fi
      - run:
          name: build
          command: npm run build
